### ISSUE TITLE
Document how to run this

### ISSUE THREAD

**Issue by Lykos** [gowerc/aoecps#14]
Hello,

I saw that your data only includes Arabia, but I would like to know the same things for other maps. If there would be documentation on how to run this, I could probably do that myself.

**Comment by gowerc** [comment]
Heya, 

Thanks for your interest, will try to add something to the README later to provide instructions. In terms of rerunning the code the only prerequisite is docker + docker-compose. Once you have those you just need to run following:

- Clone the project
- Launch the containers via `docker-compose up -d`
- Enter the analysis container via `docker exec -it aoecps_analysis_1 bash` (container name may differ but you can check this via `docker container ls`)
- Build the database via `snakemake -j1 dbupdate` (this will take a long time in its current setup as it only performs 1 active request at a time to be friendly to the remote server and each request only retrieves 1k records with there being something like 3million+ matches available atm)
- Build the report `snakemake -j1 outputs/report.html`

To be clear I am running this all on Ubuntu Focal, if memory serves me right windows has some issues with mounting the host file system within the container.

In terms of the Arabia filter it can be found [here](https://github.com/gowerc/aoecps/blob/fa0438bd22bed846b95b3675a72c77416a2aeb3a/analysis/ad_ia.R#L51) for individual games and [here](https://github.com/gowerc/aoecps/blob/fa0438bd22bed846b95b3675a72c77416a2aeb3a/analysis/ad_ta.R#L28) for team games.

Though apologies, I just tried rebuilding the report and it looks like some of the more recent matches have broken some of my assertions in `ta_bt_civ.R` (this creates the team game outputs for civ comparisons on the bradly terry  model). Will try and fix this sometime this week.

**Comment by gowerc** [comment]
Have updated the code with the following:
- Fixed the aforemention error message ensuring the report can be built from scratch
- Updated the database build code to no longer require any manual processes
- Added readme instructions on how to run the project


Hopefully this should address this issue feel free to add a comment or a new issue if you have any further questions
